import { Inter } from 'next/font/google';
import './globals.css';

// ✅ クライアント側で lang を切り替えるコンポーネント
import SetLangTag from './SetLangTag';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // ✅ lang属性を削除し、ハイドレーションエラーを防ぐ
    <html>
      <body className={inter.className}>
        <SetLangTag /> {/* ✅ クライアント側で lang を設定 */}
        {children}
      </body>
    </html>
  );
}
